AWSTemplateFormatVersion: '2010-09-09'
Description: Single EC2
Parameters:
  ImageId:
    Type: String
  InstanceType:
    Type: String
  SSHLocation:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  HostedZoneId:
    Type: String
  HostName:
    Type: String
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      CreditSpecification:
        CPUCredits: standard
      IamInstanceProfile: !Ref RootInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2Instance
      SecurityGroups:
        - !Ref EC2SecurityGroup
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: RootRole
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  CertbotPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CertbotPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - route53:ListHostedZones
              - route53:GetChange
            Resource: '*'
          - Effect: Allow
            Action:
              - route53:ChangeResourceRecordSets
            Resource: !Sub arn:aws:route53:::hostedzone/${HostedZoneId}
      Roles:
        - Ref: RootRole
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ElasticIP
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref HostName
      Type: A
      TTL: 60
      HostedZoneId: !Ref HostedZoneId
      ResourceRecords:
        - !Ref ElasticIP
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt EC2Instance.AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
  ElasticIP:
    Description: Elastic IP address of the EC2 instance
    Value: !Ref ElasticIP
